### ISSUE TITLE
Falsely accused - Emperor Nichijao

### ISSUE THREAD

**Issue by Touhou2006** [anaemicelle/tf2bd#1]
Hi! I'm writing to let the repository owner know that I have been false accused of cheating.

I would like to explain myself.

the first URL is a fabricated fake video made by I assume one of my old enemies that used to harass me a lot. A statement alone needs evidence right? 

Alright. 
![image](https://github.com/user-attachments/assets/02109743-7ca3-4ec0-a730-a4989713e0d7)

it claims that it matches my editing style and viewmodels and hud
however, on my video (right) it literally shows me using the **default sniper animations** and the **orange box console hud**.
and on the false video (left) it is using the **custom sniper animations** with the **default hud** and **madoka magica icon**.
![image](https://github.com/user-attachments/assets/49ca2b3c-fce0-4911-8e5d-9f855c95d65d)
on the left fake video, it using an FOV of 90 for the viewmodel
and for my video which is on the right, I use a FOV of 70
While there are also other similarities, it is pretty easy to replicate.

Remember that correlation does not equal causation. 

           Sincerely, Emperor Nichijao

**Comment by anaemicelle** [comment]
Sure, I can remove it on principle, since we're not marking people with SourceBans for cheating years ago if they're not doing it anymore, and it's obviously someone with a vendetta if they bothered saving your video. But also on principle, it'd be inappropriate not to mention that it _is_ [you](https://backpack.tf/profiles/76561199204890685?time=1638316800) in the video. Or, in any event, this "impersonator" is [quite dedicated](https://i.imgur.com/YYAr3hk.png) to using names of the same style and even [matching](https://archive.is/rqa9v) your [ping](https://archive.is/QqhW3) [range](https://archive.is/btwUK). And check his screenshots--looks like he's been [stealing your visuals](https://archive.is/1AP0k) for years! Hard to blame him for being a tiny bit off.

No need to make me bother double-checking the account if you could have just admitted "yeah, I cheated to fuck with this guy three years ago and he's still mad, never touched them on my main". It's a shame the submitter neglected to archive the video on the channel itself.

**Comment by Touhou2006** [comment]
Thank you. Admittingly I am a former vigilante years ago because valve did not do anything about the cheater and harassment scene, but I stopped for personal reasons and hasn’t used modified software since.

Cammy White is my account, however for recent times I mostly only used it for idling 

once again, I am sorry for making you double check the account.

have a nice day
