### ISSUE TITLE
On the topic of "<name> joined team RED"

### ISSUE THREAD

**Issue by HyreHigher** [anaemicelle/tf2bd#2]
You have mentioned that you were using this as a way to mark potential cheaters, but it is quite flawed.

This is very easy to replicate, and it is done so through typing "spectate" in console before you are prompted with the ability to join a class. 
On occasion, TF2 may have a problem in Casual when joining a server, where you will be stuck a weird spectate limbo, unable to choose a class, and in this situation, you can re-connect to the server to fix the bug, but myself and recently some of my friends (specifically [this friend](https://steamhistory.net/id/76561199180592181) who was marked) use the "spectate" command in console to fix this bug. 

It is possible that some cheats, such as the "nullcore" cheat mentioned on the mark automatically use this command, which could explain the association, but I have had the spectate bug happen quite recently, alongside some of my friends, and I generally give the advice of "spectate" in console instead of "retry" as it is simple and faster than a re-connect.

Here's a screenshot proving that I could do so myself, and I'm sure it should be easily replicated by you or anyone else who may read.
[https://imgur.com/8vG5KHR](https://imgur.com/8vG5KHR)
(Also embedded at bottom of the post)

I'd be very interested in knowing if you can provide other evidence of my friend cheating, as I'm aware of their history but have been under the impression that they have in the years since their last bans stopped cheating.

Thank you! 
Hyre

![image](https://github.com/user-attachments/assets/97363c2d-56c6-4a49-845b-52e5a6b9f731)

**Comment by HyreHigher** [comment]
Oh, and in case you wanted specific steps on how I did it:

1. Queue to a casual server.
2. Load into server.
3. BEFORE closing the MotD, open console through the keybind (I believe ESC will close MOTD and open class select menu, so use ~ or your console bind.)
4. type "Spectate" in console.
5. Look at chat.

**Comment by anaemicelle** [comment]
Thanks for letting me know. This must be a new bug (or the solution is new), since I never saw this before the past month or two, as the main page says. But it has already been happening much more often than before; Nullcore is a very rare cheat to see and the people using it are never closeting, so I was befuddled enough to remove the listings, as they seemed totally legit. 

In any event, it looks like your friend was already removed before you submitted this, so there's not much I can do there; SH pulls the lists and keeps them in its own DB or something like that. Unfortunately, your friend will need to get a new account if he wants a clean SH, as Uncletopia never removes people, ever, and Skial has a similar policy on cheating.

**Comment by HyreHigher** [comment]
That's okay. Thank you for the info! I've been using that solution for a few years now but no one ever seems to bring it up, I suppose because it's an obscure command.
